# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KyiNQTW74NpA37_Fob7ml3_4rkwwCnm5

**TASK 1: Operator Implementation in Python**

***1. Arithmetic Operators***
"""

a = 8
b = 7
print("Addition: ", a+b)
print("Substraction: ", a-b)
print("Multiplication: ", a*b)
print("Division: ", a/b)
print("Floor Division: ", a//b)
print("Modulo: ", a%b)
print("Power: ", a**b)

"""***2. Relational Operators***"""

a = 8
b = 7
print("a>b : ", a>b)
print("a<b : ", a<b)
print("a>=b : ", a>=b)
print("a<=b : ", a<=b)
print("a!=b : ", a!=b)
print("a==b : ", a==b)

"""***3. Logical Operators***"""

a = True
b = False
print("a and b : ", a and b)
print("a or b : ", a or b)
print("not b : ", not b)
print("not a : ", not a)

"""***4. Bitwise Operators***"""

a = 8
b = 7
print("a&b : ", a&b)
print("a|b : ", a|b)
print("~a : ", ~a )
print("~b : ", ~b)
print("a^b : ", a^b)
print("a>>2 : ", a>>2)
print("a<<2 : ", a<<2)

"""***5. Assignment Operators***"""

a = 81
b = 71

c  = a+b
print(" = ", c)

c += 2
print("+= : ", c)

c -=2
print("-= : ", c)

c *= 2
print("*= : ", c)

c /= 2
print("/= : ", c)

c //=2
print("//= : ", c)

c %=2
print("%= : ", c)

c = 118
c &= 2
print("&= : ", c)

c |=2
print("|= : ", c)

c ^= 2
print("^= : ", c)

c >>= 2
print(">>= : ", c)

c <<= 2
print("<<= : ", c)

"""***6. Identity Operators***"""

a = "Hello"
b = "Hello"
print("a is b : ", a is b)
print("a is not b : ", a is not b)
c = [1,2,3]
d = [1,2,3]
print("c is d : ", c is d)
print("c is not d : ", c is not d)

"""***7. Membership Operators***"""

a = [23,56,22,12,55,78,100]
print("23 in a : ", 23 in a)
print("13 not in a : ", 13 not in a)